### ISSUE TITLE
Container for content is not wide enough for the content

### ISSUE THREAD

**Issue by dmsimard** [redhat-openstack/website#231]
On Chrome 46 and Firefox 42, the width of the container in which the documentation content is in does not look wide enough: content is truncated for example on this page:  [https://www.rdoproject.org/install/quickstart/](https://www.rdoproject.org/install/quickstart/): 

I'm no CSS guru but the padding from the left side until the content begins looks needlessly large and could probably be reduced ? Here's a screenshot:

![screenshot](http://i.imgur.com/V60y6GG.png)

**Comment by apevec** [comment]
I cannot reproduce this on F22 with either Chrome 46.0.2490.86  or Firefox 42.0 even when zooming in and out.

**Comment by apevec** [comment]
But large left margin does look like a waste of screen real estate!

**Comment by dmsimard** [comment]
This looks pretty bad on a lot of pages. Can we fix this ?

Also have the same problem with the community page.
![screenshot from 2015-12-07 20-23-21](https://cloud.githubusercontent.com/assets/1291204/11645208/7a96d772-9d20-11e5-8e1f-662a063c14a4.png)

**Comment by mscherer** [comment]
Margin doesn't always mean that's a waste of space, since we do not want to have too long lines (too long line make the text harder to read, and there is various empirical measure showing that 75/100 chars are the limit). Now, it could indeed be rebalanced somehow, since there is a much wider margin on the left than on the right, and this look weird. 

I can also reproduce the truncated text issue on Firefox on RHEL 7 ( 38.4.0 )

**Comment by dmsimard** [comment]
@mscherer I agree that lines shouldn't be too long but what's happening here is that the container is seemingly too large and the text doesn't wrap where it should be. It's like the container ends off-screen.

**Comment by rbowen** [comment]
The pages that look like this have something in the header that says "pullheadings" that applies this style. I'm removing them.
