### ISSUE TITLE
Stats JSON file returns forbidden

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/website#401]
https://www.rdoproject.org/stats/browser/data/json/ returns FORBIDDEN. I presume this is just file permissions on the server side?

**Comment by mscherer** [comment]
So, trying to debug this, I uncovered a more complex problem involving a few bugs in my playbook, and in ansible (regarding variable scoping). This forced me to shave so much yaks that if I were a viking, the story of this bug would be in Edda. 

But I am not, so I will skip the details and say that once I managed to fix the problem I found (or rather, the unholy mess that I uncovered), the problem is just the lack of index.html file in this directory.

I am adding the required indexes as I type that answer, and will close accordingly.
