### ISSUE TITLE
Create new redirects

### ISSUE THREAD

**Issue by pmkovar** [redhat-openstack/website#422]
Please create new redirects for the pages that have been recently moved or removed: 

/community/adding-new-content
->
/community

/case-studies/osas-test-lab
->
/user-stories

/case-studies
->
/user-stories

**Comment by mscherer** [comment]
So I think the easiest would be to edit the website:

Just do like this https://github.com/redhat-openstack/website/blob/master/source/.htaccess.haml#L559

**Comment by rbowen** [comment]
So, it's at least worth pointing out this comment from that .htacess file:

  # Note .htaccess files are an overhead, this logic should be in your Apache
  # config if possible: httpd.apache.org/docs/2.2/howto/htaccess.html

And, as the person that actually wrote that howto document ... well, I agree with the comment. :-)

**Comment by mscherer** [comment]
So I did a bench (regular ab) with and without the file, and I see kinda no significant differences on our server.

So the choice is mostly between self service or making me do more work, and i rather vote for "less work for the admin".

**Comment by mscherer** [comment]
In fact, doing more complete bench with ab, I would estimate that we would be around 20 to 30 ms slower with the AllowOverride being activated that if we disable it. I see worst time if I start to use 10 concurrents requests, but I suspect that's more a side effect of conservative settings regarding the number of workers than anything else.

Looking with both ab and firefox, we download the html code in something like 400 ms, so 20 to 30 ms is both a lot and not a lot. Now, what matter is the rendering of the page rather than the time to download, and then, the biggest offender is the omniture tracker who slow everything down (and that's me using noscript, so I do not even know if it do slow more).

So if performance start to matter more, we can move redirect to the apache config for sure, but then, maybe the biggest problem is not the .htaccess.

**Comment by rbowen** [comment]
Noted. Thanks.

**Comment by rbowen** [comment]
@pmkovar give it a few minutes to build and deploy, and then verify that this does what you had in mind. Thanks.

**Comment by rbowen** [comment]
All appear to work. Closing ticket. Let me know if we need to add more.
